---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-demo-connecterp
  namespace: oficina5
  labels:
    app: api-demo-connecterp
  annotations:
    # Container Image Automated Updates
    flux.weave.works/automated: "true"
    # do not apply this manifest on the cluster
    #flux.weave.works/ignore: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-demo-connecterp
  template:
    metadata:
      labels:
        app: api-demo-connecterp
    spec:
      containers:
      - name: api-demo-connecterp
        image: 837042927026.dkr.ecr.us-east-2.amazonaws.com/corporate-qas:33cfea765bc0e015a72bf4520fa22935c01c0caa
        env:
        - name: CONN_DB
          valueFrom:
            secretKeyRef:
              name: api-demo-connecterp
              key: CONN_DB
        - name: CONN_HOST
          valueFrom:
            secretKeyRef:
              name: api-demo-connecterp
              key: CONN_HOST
        - name: CONN_PASS
          valueFrom:
            secretKeyRef:
              name: api-demo-connecterp
              key: CONN_PASS
        - name: CONN_USER
          valueFrom:
            secretKeyRef:
              name: api-demo-connecterp
              key: CONN_USER
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
