---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-ercal-qas
  namespace: oficina5
  labels:
    app: api-ercal-qas
  annotations:
    # Container Image Automated Updates
    flux.weave.works/automated: "true"
    # do not apply this manifest on the cluster
    #flux.weave.works/ignore: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-ercal-qas
  template:
    metadata:
      labels:
        app: api-ercal-qas
    spec:
      containers:
      - name: api-ercal-qas
        image: 837042927026.dkr.ecr.us-east-2.amazonaws.com/corporate-qas:3c01cd5a6b496309259d573cb9420051c3324e09
        env:
        - name: CONN_DB
          valueFrom:
            secretKeyRef:
                name: api-ercal-qas
                key: CONN_DB
        - name: CONN_HOST
          valueFrom:
            secretKeyRef:
                name: api-ercal-qas
                key: CONN_HOST
        - name: CONN_PASS
          valueFrom:
            secretKeyRef:
                name: api-ercal-qas
                key: CONN_PASS
        - name: CONN_USER
          valueFrom:
            secretKeyRef:
                name: api-ercal-qas
                key: CONN_USER
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
