---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuvme
  namespace: oficina5
  labels:
    app: nuvme
  annotations:
    # Container Image Automated Updates
    flux.weave.works/automated: "true"
    # do not apply this manifest on the cluster
    #flux.weave.works/ignore: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nuvme
  template:
    metadata:
      labels:
        app: nuvme
    spec:
      containers:
      - name: nuvme
        image: nginx:1.18-alpine-perl
        env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: api-nuvme
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-nuvme
              key: password
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: api-nuvme
              key: s3bucket
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
