---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plan-agricola-dev
  namespace: oficina5
  labels:
    app: plan-agricola-dev
  annotations:
    # Container Image Automated Updates
    flux.weave.works/automated: "true"
    # do not apply this manifest on the cluster
    #flux.weave.works/ignore: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plan-agricola-dev
  template:
    metadata:
      labels:
        app: plan-agricola-dev
    spec:
      containers:
      - name: plan-agricola-dev
        image: 837042927026.dkr.ecr.us-east-2.amazonaws.com/plan-agricola-dev:eafae57fe7a27fa7d89779367c0e65837f8a4893
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1

