---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plan-agricola-dev
  namespace: oficina5
  labels:
    app: plan-agricola-dev
  annotations:
    # Container Image Automated Updates
    flux.weave.works/automated: "true"
    # do not apply this manifest on the cluster
    #flux.weave.works/ignore: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plan-agricola-dev
  template:
    metadata:
      labels:
        app: plan-agricola-dev
    spec:
      containers:
      - name: plan-agricola-dev
        image: 837042927026.dkr.ecr.us-east-2.amazonaws.com/plan-agricola-dev:d66fc723aeeb11c88b4ccaa40213bc4b974d857a
        imagePullPolicy: IfNotPresent
        env:
        - name: nuvme_env
          valueFrom: arn:aws:ssm:us-east-2:837042927026:parameter/plan-agricola-dev-NUVME
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1

