apiVersion: v1
kind: Service
metadata:
  name: eks-example2
  namespace: eks-example
  labels:
    app: eks-example2
spec:
  type: LoadBalancer
  ports:
    - port: 81
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: eks-example2
