apiVersion: v1
kind: Service
metadata:
  name: eks-example1
  namespace: eks-example
  labels:
    app: eks-example1
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: eks-example1
