apiVersion: v1
kind: Service
metadata:
  name: api-flg-qas
  namespace: oficina5
  labels:
    app: api-flg-qas
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: api-flg-qas
    #app.kubernetes.io/name: api-flg-qas
