apiVersion: v1
kind: Service
metadata:
  name: nuvme
  namespace: oficina5
  labels:
    app: nuvme
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: nuvme
    #app.kubernetes.io/name: nuvme
