apiVersion: v1
kind: Service
metadata:
  name: plan-agricola-dev
  namespace: oficina5
  labels:
    app: plan-agricola-dev
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: plan-agricola-dev
    #app.kubernetes.io/name: plan-agricola-dev
